// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0UHm4REhXfp4FBA7FyDLXL80b4Ab5rcE',
    appId: '1:822562274761:web:ac858e4b45edf05b0bfc18',
    messagingSenderId: '822562274761',
    projectId: 'boulder-league-app',
    authDomain: 'boulder-league-app.firebaseapp.com',
    storageBucket: 'boulder-league-app.firebasestorage.app',
    measurementId: 'G-HSHCPBKJ5C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxp5maPru3iL1Ukcd0sAjIzU0Ja1qlhm8',
    appId: '1:822562274761:android:a71a7fd2d78c1eb20bfc18',
    messagingSenderId: '822562274761',
    projectId: 'boulder-league-app',
    storageBucket: 'boulder-league-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtSmtW0PMydeCDwO4hJF2A8Rt-UiUNsXU',
    appId: '1:822562274761:ios:706e6c2e76bb93da0bfc18',
    messagingSenderId: '822562274761',
    projectId: 'boulder-league-app',
    storageBucket: 'boulder-league-app.firebasestorage.app',
    iosBundleId: 'com.boulderLeagueApp',
  );

}